apiVersion: apps/v1
kind: Deployment
metadata:
  name: managers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managers
  template:
    metadata:
      labels:
        app: managers
    
    spec:
      containers:
        - name: managers
          image: yassineelk/managers
